backend:
  name: git-gateway
  repo: arthurfontainecom-wq/Fiche-Securite-Final
  branch: main

media_folder: "fiches" # Tes PDF vont ici
public_folder: "/fiches"

collections:
  - name: "fiches"
    label: "Ajouter une Fiche"
    folder: "data/fiches" # Les fichiers .md de gestion iront ici, ils ne gêneront pas ton JS
    create: true
    identifier_field: title
    slug: "{{title}}"
    fields:
      - { label: "Nom de la fiche (ex: Acide Chlorhydrique)", name: "title", widget: "string" }
      - { label: "Sélectionner le PDF", name: "file", widget: "file" }
