backend:
  name: git-gateway
  repo: arthurfontainecom-wq/Fiche-Securite-Final
  branch: main

media_folder: "fiches"
public_folder: "/fiches"

collections:
  - name: "fiches_upload"
    label: "Ajouter un PDF"
    files:
      - label: "Nouveau PDF"
        name: "upload"
        file: "fiches/.keep" # Astuce pour uploader dans le dossier sans créer de .md
        fields:
          - { label: "Sélectionner le PDF", name: "pdf_file", widget: "file", media_library: { allow_multiple: false } }
