backend:
  name: git-gateway
  repo: arthurfontainecom-wq/Fiche-Securite-Final
  branch: main

media_folder: "fiches"
public_folder: "/fiches"

collections:
  - name: "upload"
    label: "Uploader mes PDF"
    files:
      - label: "Cliquez ici pour envoyer"
        name: "medias"
        file: "fiches/.gitkeep"
        fields:
          - { label: "SÃ©lectionnez vos PDF (renommez-les avant !)", name: "fichiers", widget: "file", media_library: { allow_multiple: true } }
